# Site settings
name: ZFC
email: fuchzhao@163.com
author: zhaofuchao
url: https://ZFCC.github.io
##这里原作者加了 自己个人主页链接，以及他所管理的域名
resume_site: ""
github: https://github.com/ZFCC

baseurl: ""
description: Nothing is impossible!
meta_description: 赵福超;个人博客;
motto: Nothing is impossible!
banner: 一切皆有可能。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: ZFCC

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

